
name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      # 将构建上下文指定为 neatsub 目录，Dockerfile 在该目录下
      run: docker build ./neatsub --tag neatsub:$(date +%s)
